# Generated by Django 5.2.8 on 2025-11-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultor_id', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('en_proceso', 'En Proceso')], default='pendiente', max_length=20)),
            ],
        ),
    ]
