# Generated by Django 5.2.8 on 2025-11-08 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
        ('gestion_clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='monto_total',
        ),
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='gestion_clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=20),
        ),
    ]
